prometheus:
  thanosService:
    enabled: false
  service:
    type: LoadBalancer
    targetPort: 9090
    nodePort: 30090
    annotations: {}
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    additionalScrapeConfigs:
      - job_name: 'nginx'
        static_configs:
          - targets: ['nginx.default.svc.cluster.local:9113']

alertmanager:
  enabled: true
  service:
    type: LoadBalancer
    annotations: {}
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
  config:
    global:
      resolve_timeout: 5m
    route:
      group_by: ['alertname', 'job']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: 'null'
    receivers:
      - name: 'null'

grafana:
  enabled: true
  defaultDashboardsEnabled: true
  adminPassword: admin
  service:
    type: LoadBalancer
    port: 80
    targetPort: 3000
    nodePort: 30080
  configMaps:
    - monitoring-grafana
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      searchNamespace: ALL

kubePrometheus:
  enabled: true
  configMaps:
    - monitoring-kube-prometheus-apiserver
    - monitoring-kube-prometheus-cluster-total

prometheusOperator:
  enabled: true
  admissionWebhooks:
    enabled: true
    patch:
      enabled: true

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true

additionalPrometheusRulesMap:
  nginx-rules:
    groups:
    - name: nginx.rules
      rules:
      - alert: NginxHighCPU
        expr: rate(process_cpu_seconds_total{job="nginx"}[5m]) * 100 > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Nginx high CPU usage"
          description: "Nginx CPU usage is above 80% for more than 5 minutes\n Current value: {{ $value }}%"
