apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: default
data:
  nginx.conf: |
    user  nginx;
    worker_processes  auto;
    error_log  /var/log/nginx/error.log notice;
    pid        /var/run/nginx.pid;
    events {
        worker_connections  1024;
    }
    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;
        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                         '$status $body_bytes_sent "$http_referer" '
                         '"$http_user_agent" "$http_x_forwarded_for"';
        access_log  /var/log/nginx/access.log  main;
        sendfile        on;
        keepalive_timeout  65;
        server {
            listen       80;
            server_name  localhost;
            location / {
                root   /usr/share/nginx/html;
                index  index.html index.htm;
            }
            location /metrics {
                stub_status on;
            }
        }
    }
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Welcome to Azure AKS!</title>
      <style>
        body {
          font-family: Arial, sans-serif;
          margin: 40px auto;
          max-width: 800px;
          padding: 20px;
          text-align: center;
          background-color: #f0f2f5;
        }
        h1 {
          color: #0078d4;
          font-size: 48px;
          margin-bottom: 20px;
        }
        p {
          color: #333;
          font-size: 24px;
          line-height: 1.6;
        }
      </style>
    </head>
    <body>
      <h1>Welcome to Azure AKS!</h1>
      <p>Your Nginx application is running successfully on Azure Kubernetes Service.</p>
      <p>This page is served through a Kubernetes ConfigMap.</p>
    </body>
    </html>
